
language: python
repo_token: GzdJ33Hc2nHGJefrUIeLJt8v2fOyjvgND
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python example.py
  - pytest --cov=./
after_success:
  - coveralls