

language: python
branches:
  only:
  - master
python:
  - "3.7"
cache: pip
env:
  global:
    - CC_TEST_REPORTER_ID="4700197b8114dbcdacaf089f5a7efdb731d6d068d97dc33794bf36be7536435c"
    - CODECOV_TOKEN="8c5a7154-23cc-47b7-8a7d-d94a3d2ec889"
before_install:
  - python --version
install:
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script:
  - python example.py
  - pytest example.py
  - codecov --token=8c5a7154-23cc-47b7-8a7d-d94a3d2ec889
  - coverage run --source=./ example.py
  - coveralls
after_success:
  - coveralls
